{{- if and .Values.keycloak.enabled (not .Values.keycloak.external.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencloud.keycloak.fullname" . }}-script
  namespace: {{ include "opencloud.namespace" . }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
data:
  docker-entrypoint-override.sh: |-
    #!/bin/bash
    printenv
    # replace openCloud domain in keycloak realm import
    mkdir -p /opt/keycloak/data/import
    
    # Replace domain in the realm configuration
    sed -e "s/cloud.opencloud.test/${OC_DOMAIN}/g" /opt/keycloak/data/import-dist/opencloud-realm.json > /opt/keycloak/data/import/opencloud-realm.json
    
    # run original docker-entrypoint
    /opt/keycloak/bin/kc.sh "$@"
{{- end }}
