{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameKeycloak" "appNameSuffix" "") -}}
{{ if .Values.keycloak.enabled }}
apiVersion: apps/v1
kind: Deployment
{{ include "oc.metadata" . }}
spec:
  {{- include "oc.selector" . | nindent 2 }}
  replicas: 1
  template:
    {{- include "oc.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: keycloak
          # Todo get from values
          image: {{ .Values.keycloak.image.registry }}/{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}
          imagePullPolicy: {{ .Values.keycloak.image.pullPolicy | default "IfNotPresent" }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          command: ["/bin/sh", "/opt/keycloak/bin/docker-entrypoint-override.sh"]
          args:
            - "start"
            - "--http-enabled=true"
            - "--proxy-headers=xforwarded"
            - "--hostname=https://{{ .Values.keycloak.domain }}"
            - "--spi-connections-http-client-default-disable-trust-manager={{ .Values.insecure.oidcIdpInsecure }}"
            - "--import-realm"
          env:
            - name: OC_DOMAIN
              value: {{ .Values.externalDomain }}
            - name: KC_HOSTNAME_URL
              value: "https://{{ .Values.keycloak.domain }}"
            - name: KC_DB_URL_HOST
              value: {{ .appName }}-postgresql
            - name: KC_DB_URL_DATABASE
              value: keycloak
            - name: KC_CACHE
              value: "local"
            - name: KC_CACHE_STACK
              value: "tcp"
            - name: KC_SPI_CONNECTIONS_JPA_QUARKUS_MIGRATION_STRATEGY
              value: "update"
            - name: KC_SPI_CONNECTIONS_JPA_QUARKUS_INITIALIZE_EMPTY
              value: "true"
            - name: KC_SPI_CONNECTIONS_JPA_QUARKUS_MIGRATION_CHECKSUM_VALIDATION
              value: "false"
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.keycloak.config.adminUser }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{ .Values.keycloak.config.adminPassword }}
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://{{ .Values.keycloak.postgresql.host }}:{{ .Values.keycloak.postgresql.port }}/{{ .Values.keycloak.postgresql.database }}
            - name: KC_DB_USERNAME
              value: {{ .Values.keycloak.postgresql.username }}
            - name: KC_DB_PASSWORD
              value: {{ .Values.keycloak.postgresql.password }}
            - name: KC_FEATURES
              value: impersonation
            - name: KC_PROXY
              value: edge
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: script
              mountPath: /opt/keycloak/bin/docker-entrypoint-override.sh
              subPath: docker-entrypoint-override.sh
            - name: realm-config
              mountPath: /opt/keycloak/data/import-dist/opencloud-realm.json
              subPath: opencloud-realm.json
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /realms/master
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /realms/master
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 5
      volumes:
        - name: script
          configMap:
            name: {{ .appName }}-script
            defaultMode: 0755
        - name: realm-config
          configMap:
            name: {{ .appName }}-realm
{{ end }}
