{{- if .Values.cilium.httproute.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "opencloud.fullname" . }}-httproute
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.cilium.httproute.gateway.name }}
      namespace: {{ .Values.cilium.httproute.gateway.namespace | default .Values.namespace }}
      sectionName: opencloud-https
  hostnames:
    - {{ include "opencloud.domain" . | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            remove:
              - "Permissions-Policy"
      backendRefs:
        - name: {{ include "opencloud.opencloud.fullname" . }}
          port: 9200
{{- end }}
